[package]
name = "antv-layout"
version = "0.0.1"
authors = ["antv"]
edition = "2018"
license = "MIT"
description = "A flexible force-directed graph framework"
repository = "https://github.com/antvis/layout"
documentation = "https://observablehq.com/d/2db6b0cc5e97d8d6"
keywords = ["graph", "layout", "viz"]
categories = ["visualization"]
readme = "README.md"

[profile.release]
panic = 'abort'
lto = true
opt-level = 's'

[dependencies]
atoi = "2.0.0"
atomic = "0.5.1"
atomic_float = "0.1.0"
byte-slice-cast = "1.2.2"
delegate = "0.8.0"
itertools = "0.10.3"
fast-float = "0.2.0"
rayon = "1.5.1"
parking_lot = "0.12.1"
thiserror = "1.0.37"
page_size = "0.4.2"
num_cpus = "1.14.0"
memmap2 = "0.5.8"

[dev-dependencies]
alloc_counter = "0.0.4"
plotters = "0.3.1"
scanrs = "0.3.0"
sdl2 = "0.35.2"
stl = { git = "https://github.com/etrombly/rust-stl" }

