[package]
name = "antv-layout"
version = "0.0.1"
authors = ["antv"]
edition = "2018"
license = "MIT"
description = "A flexible force-directed graph framework"
repository = "https://github.com/antvis/layout"
documentation = "https://observablehq.com/d/2db6b0cc5e97d8d6"
keywords = ["graph", "layout", "viz"]
categories = ["visualization"]
readme = "README.md"

[profile.release]
codegen-units = 1
debug = true

[dependencies]
itertools = "0.10.3"
maths-traits = "0.2.1"
num-traits = "0.2.14"
rayon = "1.5.1"

[dev-dependencies]
alloc_counter = "0.0.4"
plotters = "0.3.1"
scanrs = "0.3.0"
sdl2 = "0.35.2"
stl = { git = "https://github.com/etrombly/rust-stl" }

