name: build

on: ["push", "pull_request"]

jobs:
  ci:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: build
        run: npm run build

      - name: test
        run: npm test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
            token: ${{ secrets.CODECOV_TOKEN }}
            slug: antvis/layout
